add_library(OTTERUS_CORE STATIC
    Core/CoreUtilities/CoreEngineData.cpp
    Core/CoreUtilities/CoreEngineData.h
    Core/CoreUtilities/FollowCamera.cpp
    Core/CoreUtilities/FollowCamera.h
    Core/ECS/Components/AnimationComponent.cpp
    Core/ECS/Components/AnimationComponent.h
    Core/ECS/Components/BoxColliderComponent.cpp
    Core/ECS/Components/BoxColliderComponent.h
    Core/ECS/Components/CircleColliderComponent.cpp
    Core/ECS/Components/CircleColliderComponent.h
    Core/ECS/Components/Identification.h
    Core/ECS/Components/PhysicsComponent.cpp
    Core/ECS/Components/PhysicsComponent.h
    Core/ECS/Components/RigidBodyComponent.cpp
    Core/ECS/Components/RigidBodyComponent.h
    Core/ECS/Components/ScriptComponent.h
    Core/ECS/Components/SpriteComponent.cpp
    Core/ECS/Components/SpriteComponent.h
    Core/ECS/Components/TextComponent.cpp
    Core/ECS/Components/TextComponent.h
    Core/ECS/Components/TransformComponent.cpp
    Core/ECS/Components/TransformComponent.h
    Core/ECS/Entity.cpp
    Core/ECS/Entity.h
    Core/ECS/Entity.inl
    Core/ECS/MainRegistry.cpp
    Core/ECS/MainRegistry.h
    Core/ECS/MetaUtilities.cpp
    Core/ECS/MetaUtilities.h
    Core/ECS/Registry.cpp
    Core/ECS/Registry.h
    Core/ECS/Registry.inl
    Core/Scripting/ContactListenerBind.cpp
    Core/Scripting/ContactListenerBind.h
    Core/Scripting/GlmLuaBindings.cpp
    Core/Scripting/GlmLuaBindings.h
    Core/Scripting/InputManager.cpp
    Core/Scripting/InputManager.h
    Core/Scripting/RendererBindings.cpp
    Core/Scripting/RendererBindings.h
    Core/Scripting/SoundBindings.cpp
    Core/Scripting/SoundBindings.h
    Core/Scripting/UserDataBindings.cpp
    Core/Scripting/UserDataBindings.h
    Core/Scripting/UserDataBindings.inl
    Core/States/State.cpp
    Core/States/State.h
    Core/States/StateStack.cpp
    Core/States/StateStack.h
    Core/Systems/AnimationSystem.cpp
    Core/Systems/AnimationSystem.h
    Core/Systems/PhysicsSystem.cpp
    Core/Systems/PhysicsSystem.h
    Core/Systems/RenderShapeSystem.cpp
    Core/Systems/RenderShapeSystem.h
    Core/Systems/RenderSystem.cpp
    Core/Systems/RenderSystem.h
    Core/Systems/RenderUISystem.cpp
    Core/Systems/RenderUISystem.h
    Core/Systems/ScriptingSystem.cpp
    Core/Systems/ScriptingSystem.h
    Core/Resources/AssetManager.cpp
    Core/Resources/AssetManager.h
)

target_include_directories(OTTERUS_CORE PUBLIC
    "${CMAKE_CURRENT_SOURCE_DIR}"
)


target_link_libraries(OTTERUS_CORE PUBLIC
    OTTERUS_LOGGER
    OTTERUS_UTILITIES
    OTTERUS_WINDOW
    OTTERUS_SOUND
    OTTERUS_RENDERING
    OTTERUS_PHYSICS
    EnTT::EnTT
    GLM::GLM
    Sol3::Sol3
    Lua53::Lua53
    SDL2::SDL2
    SDL2::SDL2_mixer
    Box2D::Box2D
)
